
spring:
  #  热部署端口
  devtools:
    livereload:
      port=35730:
  #thymleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/secondkill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 10
      default-auto-commit: true

#reids配置
  redis:
#    主机
    host: 192.168.98.130
#    端口
    port: 6379
#    数据库
    database: 0
#    超时时间
    timeout: 10000ms
    lettuce:
      pool:
#       最大连接数
        max-active: 8
#        最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
#        最大空相连接。默认8
        max-idle: 200
        min-idle: 1


  # RabbitMQ
  rabbitmq:
    # 服务器
    host: 192.168.98.130
    #用户名
    username: admin
    #密码
    password: admin
    # 虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数。比如配2.0，第一次就等10s，第二次就等20s，第三次就等40s
        multiplier: 1

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wjy.secondkill.entity

#mybatis SQL打印
logging:
  level:
    com.wjy.secondkill.mapper: debug


